include:
  - ./composes/compose.yaml

services:
  vk-hack-recsys:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vk-hack-recsys
    environment:
      - VALKEY_HOST=valkey
      - VALKEY_PORT=6379
      - VALKEY_DB=0
    ports:
      - '8080:8080'
    depends_on:
      - valkey
    command: poetry run python -m src.api.grpc.run_server