services:
  valkey:
    image: valkey/valkey:9.0-alpine
    container_name: valkey
    ports:
      - '6379:6379'
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '512M'